# Taille d'une case
SQUARE_SIZE = 80

# Plateau 8x8
BOARD_COLS = 8
BOARD_ROWS = 8
BOARD_WIDTH = SQUARE_SIZE * BOARD_COLS
BOARD_HEIGHT = SQUARE_SIZE * BOARD_ROWS

# Marges autour
BOARD_OFFSET_X = 150
BOARD_OFFSET_Y = 80

# Fenêtre
WIDTH = BOARD_WIDTH + 2 * BOARD_OFFSET_X
HEIGHT = BOARD_HEIGHT + 2 * BOARD_OFFSET_Y

# Thème
LIGHT = (186, 202, 68)
DARK = (118, 150, 86)
